### ISSUE TITLE
Stats/rankings for multi-regional countries

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#233] opened 2017-09-01 15:08 UTC

**Comment by jteresco** [comment] 2017-09-01 15:08
http://tm.teresco.org/forum/index.php?topic=2204.0

**Comment by yakra** [comment] 2020-05-07 15:53
Should this be considered a duplicate of #54?

**Comment by michihdeu** [comment] 2020-05-07 16:25
IT is a little bit more: 

> It doesn't have to be limited to multi-region countries either - continents are something we can do in the same way.

But I'll add this to #54

**Comment by yakra** [comment] 2020-05-07 18:31
Closing as a duplicate of #54

**Closed by yakra** 2020-05-07 18:31 UTC
Labels: Userpages, enhancement
