### ISSUE TITLE
mapview route highlighting in Firefox

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#353] opened 2019-09-21 17:00 UTC
When a mapview page is loaded or refreshed and the mouse pointer is hovering over a line on the Route Table, that route will be highlighted on the map when it fully loads. Moving the mouse to hover over different routes (or none) will and & remove additional highlights as expected, but the original highlight will not go away.

Observed in Firefox (69.0 on Ubuntu 16.04 & 18.04), but not Chromium.
This appears to be rooted in how different browsers handle their Javascript, so this may be difficult (even possible?) to fix.

**Comment by jteresco** [comment] 2020-05-23 20:02
Should not happen in Scrollable Mapview, as the highlighting is done in a different way.  The new engine might become the default down the road, so this issue could become irrelevant at that time.

**Comment by yakra** [comment] 2020-06-06 02:18
Yep. I'm no longer experiencing the problem. I'll leave it to @jteresco to close this, either now or when the new engine becomes the default or whenever.

**Comment by yakra** [comment] 2020-06-08 04:19
It's back, with a vengeance. :(
![screenshot](http://yakra.teresco.org/images/mapview_route_highlighting.png)
I got this by hovering the mouse pointer over the the headers for individual systems, and pressing `-` and `+` on the number pad to zoom and thus reload. I can move the pointer around, and highlights will appear and disappear normally... but whatever the pointer is on when the `Loading Data...` message disappears stays highlighted. Even when I scroll the offending polylines off the ends of the map and scroll back.

**Comment by jteresco** [comment] 2020-06-08 11:37
Made a quick fix, can you see if it still happens in your situations?

**Comment by yakra** [comment] 2020-06-09 20:48
If I place the mouse pointer over the table and then press `+` or `-` to zoom or arrow keys to pan, the gray highlight disappears while the zoom or pan operation is completed. When `Loading Data...` disappears, the gray highlight is drawn.
We're good as along as I don't move the mouse during the process.
If I quickly move the mouse over the table, highlight appear/disappear normally again, with highlights lingering as described above.
By waving the mouse around super-fast, I ended up with multiple routes highlighted.
![NH_highlights](https://user-images.githubusercontent.com/13720877/84198040-f31c5200-aa70-11ea-80bf-15ef2f45be20.png)

**Comment by jteresco** [comment] 2020-12-30 21:21
An update after looking at this for a few minutes.  I can reproduce the problem (if I understand it correctly) on my Mac in both Firefox and Chrome.  Idea: ignore the route table hover events while data is being loaded.

**Comment by jteresco** [comment] 2020-12-30 22:18
That might have worked.  I can't reproduce the stray highlight overlays in my first few minutes of testing, anyway.  The change is pretty harmless otherwise, so it's right up there on the production server for testing.

**Comment by jteresco** [comment] 2024-06-09 02:11
I think I just forgot to close this, and I can't reproduce the problem reported, so I'm closing.

**Closed by jteresco** 2024-06-09 02:11 UTC
Labels: bug, Mapview
