### ISSUE TITLE
bela shields

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#590] opened 2021-01-13 18:06 UTC
The text in the shields appears to be right justified.  Please close if this behavior is correct.

**Comment by michihdeu** [comment] 2021-01-13 18:10
Looks good.

**Comment by jteresco** [comment] 2021-01-13 18:42
Reopening because there is a problem with bela shields in showroute.

https://forum.travelmapping.net/index.php?topic=288.msg21754#msg21754

**Comment by michihdeu** [comment] 2021-02-07 14:52
The bug is a duplicate of #615 (hunm + belb)

"A1
  " including line break.

**Comment by michihdeu** [comment] 2021-10-29 18:55
The spaces and line break are still there, but it looks good on showroute now.

**Closed by michihdeu** 2021-10-29 18:55 UTC
Labels: bug, help wanted, Shield Generator
