### ISSUE TITLE
Scrollable Mapview: Need markers at all?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#425] opened 2020-05-23 04:04 UTC
I have not put Markers into the new Mapview functionality from #212.  Does anyone care?  It's not hard but if no one ever uses them I won't put in the effort and won't add all the Marker objects and the memory and computational costs that come along.

**Comment by michihdeu** [comment] 2020-05-23 19:23
I cannot see the option for the current mapview version. And I don't need them on mapview...

**Comment by jteresco** [comment] 2020-05-23 19:29
In current mapview, it's pretty well hidden from the average user.  Choose "Show Map Options" and you can turn on Markers.

**Comment by michihdeu** [comment] 2020-05-23 19:38
Thanks. I don't need it and don't think that anyone needs it. The info is also incorrect because it only refers to one route. It is really **not** useful.

**Comment by yakra** [comment] 2020-05-25 16:48
I use the feature sometimes, but not too often.
As @michihdeu notes, the waypoint label shown is that of one route only, and use is limited.

In the OP, @jteresco wrote:
> I won't put in the effort and won't add all the Marker objects and **the memory and computational costs that come along**.

That's the big question for me. Memory is less of an issue, but how much would it degrade performance? Even with `Show Markers` disabled?
Right now the new mapview is pretty fast for what it has to do, and quite responsive while I pan and zoom around. It would be a shame to sacrifice that speed. If mapview were to run slower with `Show Markers` disabled, I'd say leave the feature out. For those rare times I actually do use the feature, I can adapt & get the info I need elsewhere.

**Comment by michihdeu** [comment] 2020-05-25 17:01
> Right now the new mapview is pretty fast for what it has to do, and quite responsive while I pan and zoom around.

I don't agree. It's slow and it hung when I tried this morning. Need to reproduce the issue and report.....

**Comment by jteresco** [comment] 2020-05-25 19:06
If I decide to add Markers, they would have the labels for all concurrent and intersecting routes that share the point.

**Comment by michihdeu** [comment] 2020-06-02 19:17
I think that markers are not requested by anyone. Not here, not on forum. Closing?

**Closed** 2020-06-07 19:18 UTC
Labels: Mapview, question
