### ISSUE TITLE
Sorting of Routes in User Pages

### ISSUE THREAD

**Issue by vdeane** [TravelMapping/Web#53] opened 2016-04-03 18:12 UTC
The sorting of routes in the user pages is odd.  They sort rather poorly with a straight alphabetical sort, so that some systems (such as US Select Named Freeways) are scattered throughout the list and routes aren't ordered correctly (for example, NY goes "NY 10, NY 100, NY 101, ..., NY 2").  This appears to not be a problem in the HB.  They should be grouped by system (should be easy with MYSQL) and sorted as they are in the HB.

**Comment by ssoworld** [comment] 2016-04-04 02:29
Recommend a regex sort including leading zeros (3-5 depending on route number range)

**Comment by yakra** [comment] 2016-04-04 04:47
Sort based on the order in the CSVs -- US1AltYor, US1AltPor, US1AltRoc, US1AltBan, US1AltMil, US1AltMac, US1AltFor...

**Comment by jteresco** [comment] 2016-07-04 14:51
Is everything you need to do this already in the DB?  If you need a sequence numbering on the able entries for anything, let me know.

**Comment by Thing342** [comment] 2016-07-04 15:26
If my understanding of the problem is correct, this just occurs in region.php (where there is no root column to sort by). I just modified the SQL query to get the root and system tier and added sortable root and system tier columns. These changes should be in a forthcoming pull request.

**Comment by Thing342** [comment] 2016-07-06 01:41
Has this been properly resolved for you all on tmtest? If so, I'll close the issue.

**Comment by vdeane** [comment] 2016-07-06 11:40
Looks good on tmtest.

**Closed** 2016-07-06 14:56 UTC
Labels: bug
