### ISSUE TITLE
Images not rendering correct font

### ISSUE THREAD

**Issue by ssoworld** [TravelMapping/Web#28] opened 2016-01-03 17:36 UTC
for individual routes, the shield image is not rendering the FWHA font in the hb page for the route, however when I open the image itself (via "open image in new tab" on Chrome) the font is correct.  My thought is that the page CSS is overriding the font for it.  Recommend adding a new CSS rule for the image.

page for example: view-source:http://tmtest.teresco.org/devel/hb.php?u=master_son&r=wi.us141flo renders font incorrectly
image source for example: view-source:http://tmtest.teresco.org/shields/?r=wi.us141flo shows correct font

**Comment by ssoworld** [comment] 2016-01-03 17:37
I found that http://www.aaroads.com/forum/index.php?topic=17184.msg2117149#msg2117149 shows the writer is aware of this issue.

**Comment by Thing342** [comment] 2016-01-03 18:45
It's an issue with browsers not displaying external files or fonts referenced within SVGs when used in an <img> tag, presumably for security reasons. If you have the Roadgeek 2014 fonts installed, they should appear normal. I'm currently trying to figure out a 'clean' workaround (short of embedding the entire font into the SVG).

**Comment by Thing342** [comment] 2016-01-04 22:51
Should be fixed now. shields/index.php now contains a function that outputs the svg for the shield that can be included into other pages.

**Comment by jteresco** [comment] 2016-01-04 23:38
Do you think the best way to get this in is through a pull request from the master branch of your fork?

**Comment by Thing342** [comment] 2016-01-05 01:32
It (should) already be on there: fb9acdaf600d9ce8de7b21a9b60806ca894858e3

**Comment by jteresco** [comment] 2016-01-05 02:19
OK, good.  I didn't notice you'd committed to the TravelMapping master.  I'll pull down and put it on the server, thanks!

**Comment by yakra** [comment] 2016-01-06 16:19
Right now, I'm not getting any shield, just ALT text. (Firefox 43.0.3 on Ubuntu.) Is this the case for anyone else?

**Comment by ssoworld** [comment] 2016-01-06 22:53
I also have the problem - Chrome on Windows *gasp* 10

**Comment by Thing342** [comment] 2016-01-07 00:51
Works on my copy of master, but not what's on the site. Not totally sure what the issue is

**Comment by Thing342** [comment] 2016-01-07 00:56
Shields issue split into #32.

**Comment by theFXexpert** [comment] 2016-01-07 18:01
The shields still are not rendering the correct font. From what I can tell, $svgdefs in generate() is initialized but isn't echoed.

**Comment by Thing342** [comment] 2016-01-17 16:50
The issue is that the /fonts/roadgeek.css file which specifies the fonts (and stylizes the svg) is not in the live webpage despite being in the code, for whatever reason.

**Comment by jteresco** [comment] 2016-01-17 19:41
I've re-copied the entire fonts directory contents to the server.

**Comment by Thing342** [comment] 2016-01-17 23:49
I don't think that's the issue.The  <link> tag for roadgeek.css is missing in the page-source, despite being in the master git code. Have you tried copying the /devel directory again?

**Comment by jteresco** [comment] 2016-01-18 03:11
Just uploaded the entire git master tree to the server after pulling in #36.

**Comment by yakra** [comment] 2016-01-18 06:10
Shields are looking very nice on my system now!

**Comment by Thing342** [comment] 2016-02-15 15:09
If this issue is fixed, would somebody mind closing it?

**Comment by yakra** [comment] 2016-02-15 20:28
@Thing342, you now have permission to close this, right?

**Closed** 2016-02-16 00:24 UTC
