### ISSUE TITLE
HB: Incorrect values in % column (traveled)

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#103] opened 2016-08-07 07:58 UTC
The "%" column indicated the share of travelers who have traveled the segments between waypoints.

The HB is indicating that only one traveler drove on E16 in Sweden. It's [ChrisZwolle](https://github.com/TravelMapping/UserData/blob/master/list_files/ChrisZwolle.list).

http://tm.teresco.org/hb/index.php?u=ChrisZwolle&r=swe.e16
`SWE E16 NOR/SWE E45/66`

Chris drove from the border to E45 only but the entire route is indicated in "%" column to be traveled by 100% of all travelers. Only the segments b/n border and E45 should be 100%, the remaining segments should be 0%.

[Points in use](http://tm.teresco.org/logs/pointsinuse.log) also indicates that `E45/66 NOR/SWE` are used only.

Dunno what's causing the issue (maybe it's even a data processing bug?) but the E45 waypoint name has been changed. Chris is still using the alternative name in his list file!?

**Comment by michihdeu** [comment] 2016-08-08 09:33
I've traveled the concurrent R26. It's considered now because swer is "preview" now. The number of travelers is 2 now and all segments are indicated with "50%" which is also incorrect... (`NOR/SWE E45` and `R26_S R26_N` should be 50%, the remaining segments 0%).

**Comment by yakra** [comment] 2016-11-28 20:12
http://tm.teresco.org/hb/?r=ab.ab058&u=julmac
http://tm.teresco.org/hb/?r=ab.ab058&u=oscar

julmac and oscar are the only two travelers on AB58.
* julmac only has the concurrent segment of AB35 marked. No AB58 points in his LIST.
* oscar has *AB AB58 AB35_S AB88* in his LIST.

**segments & percentages:**
End AB35_S: incorrectly indicates 50%; should be 0%
AB35_S AB35_N: correctly indicates 100%
AB35_N AB88: correctly indicates 50%
AB8 *Mac/Woo*: incorrectly indicates 50%; should be 0%

(Nota bene: Mac/Woo will be relabeled as WoodBufNP soon.)

**Comment by jteresco** [comment] 2017-05-21 01:33
A little experimenting shows that this seems to happen for routes with 0 travelers with the route clinched.  I haven't found an problematic case when there is at least one traveler who has clinched the whole route.

**Comment by jteresco** [comment] 2017-05-21 02:30
The problem is with the SQL query the one at line 100 of https://github.com/TravelMapping/Web/blob/master/hb/index.php .  The "count(*)" returns 1 more than expected for some cases, seemingly only when no one has clinched the entire route.

**Comment by yakra** [comment] 2017-07-30 05:47
Another example I [posted on the forum](http://tm.teresco.org/forum/index.php?topic=2141)
http://tm.teresco.org/hb/index.php?units=miles&u=oscar&r=ns.ns366
Notice how each individual segment is listed as traveled by 100% of users.
All the other info looks correct: 1 Total Drivers ([Oscar](https://github.com/TravelMapping/UserData/search?utf8=%E2%9C%93&q=%22NS+NS366%22&type=)), with [11.29 miles](http://tm.teresco.org/user/region.php?units=miles&u=oscar&rg=NS).
Only the first two segments (from NS6_W and GreRd) should be marked as 100%; everything from BaieVerRd onwards should be 0%.

**Comment by yakra** [comment] 2018-01-05 05:15
# canmbw
taking a deeper look at the issue with a small new system that doesn't have too many people claiming mileage yet.
[As of this writing...](https://github.com/TravelMapping/UserData/commit/0d6bd246819aed0eaff34211d4a7dc99e81d541f)

**The following routes are correctly shown with 0 Total Drivers; no problems here:**
[17](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt017) [23](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt023) [25](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt025) [30](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt030) [37](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt037) [62](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt062) [70](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt070) [95](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt095) [96](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt096) [105](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt105) [125](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt125) [145](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt145) [180](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt180)

**The following routes have been clinched by at least one person, and the % column looks good:**
[47](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt047) [155](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt155)

**Total Clinched = 0:*
[42](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt42): `MB75/100` thru `MB1` OK; `Rte85` onward should be 0%
[80](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt80): `Rte90` thru `SanDr` should be 0%; BisDr OK; `Rte165` onward should be 0%
[90](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt90): `MB100` thru `BisDr` should be 0%; `Rte165` thru `MB1` OK; `WelAve` and `Rte57` should be 0%; `Rte47` OK; `MB190` should be 0%
[165](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt165): `MB90` and `MB80` OK; `Rte42` onward should be 0%

**Via multiplex:**
[20](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt20): 0 via direct .list entry, 5 via plex (MB59)
`MB100` and `Rte165` should be 100%; `MB1` onward should be 100%

[52](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt52): 3 via direct .list entry, 4 via plex (TCHMai, MB1)
`MB100` thru `Rte135` should be 0%; `MB1_E` and `Rte115` OK; `MB1_W` OK; `Rte57_E OK`; `Rte57/85` OK; `JamAve` onward OK.

[57](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt57): 1 via direct .list entry, 2 via Rte52
`Rte90` thru `Rte42` should be 0%; `Rte85_W` and `Rte52_N` OK; `Rte52_S` and `WesSt` OK; `TacAve` onward should be 0%

[85](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt85): 2 via direct .list entry, 6 via plex (TCHMai, MB1)
`MB100/101` & `StuRd` OK; `Rte96` OK; `Rte90` thru `ArlSt` OK; `MB1_E` thru `Rte62` should be 0%; `Rte42` and `Rte57_W` OK

[115](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt115): 1 via direct .list entry, 2 via plex (MB59)
`MB1` and `Rte30` OK; `MB59_S` OK; `MB59_N` onward should be 0%

[135](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt135): 0 via direct .list entry, 7 via plex (TCHMai, MB1)
`Rte62` and `Rte52` should be 0%; `MB1/150` and `Rte30` OK; `MB59` and `PleRd` OK

[150](http://tm.teresco.org/hb/index.php?u=null&r=mb.rt150): 0 via direct .list entry, 7 via plex (TCHMai, MB1)
`MB100` and `Rte165`should be 0%; MB1/135 OK

If it'd be helpful, I may take a stab at reformatting this info to mimic the HB Waypoints table, row-by-row...

**Comment by yakra** [comment] 2018-01-05 05:56
Saving these links for future reference:
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=7_8
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=dharwood
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=jeffm
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=julmac
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=kramer
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=mapcat
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=oscar
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=sipes23
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=terescoj
http://tm.teresco.org/user/mapview.php?units=miles&rg=MB&u=terminal_moraine

**Comment by yakra** [comment] 2019-09-08 14:37
To get more specific than "0 travelers with the route clinched", the misreported rows appear to be those segments that actually have 0 travelers.
I ran the query for **me.me069**, and got:
```SQL
+-----------+-----------+------------+---------------+-----------+
| pointName | latitude  | longitude  | driverPercent | segmentId |
+-----------+-----------+------------+---------------+-----------+
| ME11/100  | 44.783084 | -69.382095 |       12.5000 |    470933 |
| DetAve    | 44.782121 | -69.373518 |       12.5000 |    470934 |
| +x00001   |  44.77826 |   -69.3698 |       12.5000 |    470935 |
| +x00002   | 44.773541 | -69.347924 |       12.5000 |    470936 |
| ME220_N   | 44.792819 | -69.295986 |       25.0000 |    470937 |
| ME220_S   | 44.790828 | -69.290771 |       12.5000 |    470938 |
| RidRd     | 44.771771 | -69.243479 |       12.5000 |    470939 |
| ME7_N     | 44.767399 | -69.209737 |       37.5000 |    470940 |
| ME7_S     | 44.767048 | -69.209275 |       12.5000 |    470941 |
| +x00003   | 44.775126 | -69.190629 |       12.5000 |    470942 |
| ME143_S   | 44.781797 | -69.104165 |       25.0000 |    470943 |
| I-95(167) | 44.784637 | -69.105034 |       25.0000 |    470944 |
| ME143_N   | 44.786758 | -69.105656 |       25.0000 |    470945 |
| US2       | 44.797003 | -69.050918 |       12.5000 |      NULL |
| +x00004   |  44.77714 | -69.016655 |       12.5000 |      NULL |
| HinHillRd | 44.772947 | -68.983294 |       12.5000 |      NULL |
| I-95(174) |  44.75871 | -68.974657 |       50.0000 |    470949 |
| US202     | 44.734997 | -68.963885 |       12.5000 |    470950 |
| KenRd     | 44.698353 | -68.944461 |       12.5000 |      NULL |
| MonRd     | 44.675302 | -68.918915 |       12.5000 |      NULL |
| BosRd     | 44.670496 | -68.912714 |       12.5000 |      NULL |
| ME139_W   | 44.657027 | -68.878028 |       12.5000 |      NULL |
| LebRd     | 44.641578 | -68.854172 |       12.5000 |      NULL |
| US1Alt    | 44.633452 | -68.848615 |          NULL |      NULL |
+-----------+-----------+------------+---------------+-----------+
```
The segments with a NULL `segmentId` are the ones with no travelers, and have `driverPercent` misreported. This has got to mean something. I'll dig deeper.

**Comment by yakra** [comment] 2019-09-08 15:05
Changing the inner **SELECT**ion from `clinched.segmentId` to `segments.segmentId` fixes the NULL `segmentId` values. This will be needed for getting the cell colors right.

The main problem is still with the `count(*)`, as @jteresco [noted](https://github.com/TravelMapping/Web/issues/103#issuecomment-302910888).
We have untraveled rows to count because AIUI, the LEFT JOIN will return a row from `segments` whether or not there's a corresponding `segmentId` in the `clinched` table.

**Comment by yakra** [comment] 2019-09-08 15:35
Fix pending.

**Closed** 2019-11-09 07:08 UTC
Labels: Highway Browser, bug, help wanted, pending
