### ISSUE TITLE
WPT Editor: More datacheck error detection

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#480] opened 2020-06-11 19:32 UTC
Some of the errors (like the ones related to illegal labels) could and should be detected in the WPT Editor.

**Comment by michihdeu** [comment] 2020-06-11 19:37
Which errors do you mean? I'm only aware of #362 and #335

**Comment by michihdeu** [comment] 2020-06-11 19:39
ah, sorry! You mean NEW Data checks. But these should be done to wpt editor AND the site update scripts!

**Comment by yakra** [comment] 2020-06-11 21:21
> Some of the errors (like the ones related to illegal labels) could and should be detected in the WPT Editor.

Duplicate of #374

**Closed** 2020-06-12 07:46 UTC
Labels: WPT Editor, datacheck, duplicate, enhancement
